import discord
from discord.ext import tasks
import asyncio
import logging
from config import DISCORD_BOT_TOKEN, GEMINI_API_KEY
from scheduler import run_trading_cycle
from vision import extract_order_from_image
from agents import create_trade_management_crew, create_recovery_crew
import csv
from datetime import datetime
import os

logger = logging.getLogger(__name__)

intents = discord.Intents.default()
intents.message_content = True
client = discord.Client(intents=intents)

# Dictionary to store users we are waiting feedback from: {user_id: {"order": dict, "advice": str}}
waiting_for_feedback = {}
last_auto_plan = None  # Store the last plan generated by scheduler

def save_feedback(user_id, user_name, score, is_auto=False):
    global last_auto_plan
    
    if is_auto:
        if not last_auto_plan: return False
        order_action = "AUTO_SIGNAL"
        order_entry = last_auto_plan.exact_entry_price if hasattr(last_auto_plan, 'exact_entry_price') else 0.0
        advice = last_auto_plan.action
    else:
        feedback_data = waiting_for_feedback.get(user_id)
        if not feedback_data: return False
        order_action = feedback_data['order'].get('action')
        order_entry = feedback_data['order'].get('entry_price')
        advice = feedback_data['advice']
    
    file_exists = os.path.isfile('feedback.csv')
    with open('feedback.csv', mode='a', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        if not file_exists:
            writer.writerow(["timestamp", "user", "order_action", "order_entry", "ai_advice_action", "score"])
        
        writer.writerow([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            user_name,
            order_action,
            order_entry,
            advice,
            score
        ])
        
    if not is_auto:
        del waiting_for_feedback[user_id]
    return True

@tasks.loop(hours=4)
async def routine_loop():
    global last_auto_plan
    logger.info("Running Routine Market Update (4 Hours) via Discord loop.")
    plan = await asyncio.to_thread(run_trading_cycle, True)
    if plan and plan.action != "WAIT":
        last_auto_plan = plan

@tasks.loop(minutes=15)
async def scanner_loop():
    global last_auto_plan
    logger.info("Running Sniper Scanner (15 Minutes) via Discord loop.")
    plan = await asyncio.to_thread(run_trading_cycle, False)
    if plan and plan.action != "WAIT":
        last_auto_plan = plan

@routine_loop.before_loop
async def before_routine_loop():
    await client.wait_until_ready()

@scanner_loop.before_loop
async def before_scanner_loop():
    await client.wait_until_ready()

@client.event
async def on_ready():
    logger.info(f'Logged in as {client.user}')
    if not routine_loop.is_running():
        routine_loop.start()
    if not scanner_loop.is_running():
        scanner_loop.start()

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    logger.info(f"Received message from {message.author}: {message.content} (Attachments: {len(message.attachments)})")

    # 1. Check for feedback rating (0-10)
    if not message.attachments:
        text = message.content.strip()
        if text.isdigit() and 0 <= int(text) <= 10:
            score = int(text)
            
            # Check if it's personal image feedback first
            if message.author.id in waiting_for_feedback:
                if save_feedback(message.author.id, str(message.author), score, is_auto=False):
                    await message.reply(f"🙏 ขอบคุณสำหรับคะแนน {score}/10 ครับ! ข้อมูลนี้จะถูกนำไปพัฒนา AI ให้เก่งขึ้นครับ")
                return
            # If not personal, assume it's for the last auto signal
            elif last_auto_plan:
                if save_feedback(message.author.id, str(message.author), score, is_auto=True):
                    await message.reply(f"📈 ได้รับคะแนน {score}/10 สำหรับแผนการเทรดอัตโนมัติล่าสุดแล้วครับ! ขอบคุณมากครับ")
                return

    # 2. Check for image attachments
    if message.attachments:
        for attachment in message.attachments:
            logger.info(f"Processing attachment: {attachment.filename} (Type: {attachment.content_type})")
            
            is_image = False
            if attachment.content_type and attachment.content_type.startswith('image/'):
                is_image = True
            elif any(attachment.filename.lower().endswith(ext) for ext in ['png', 'jpg', 'jpeg', 'webp', 'heic']):
                is_image = True
                
            if is_image:
                await message.channel.send("📸 กำลังวิเคราะห์รูปภาพพอร์ตของคุณ โปรดรอสักครู่...")
                
                try:
                    # Download image bytes
                    image_bytes = await attachment.read()
                    
                    # 1. OCR Extract values
                    await message.channel.send("🔍 กำลังดึงตัวเลขจากรูปภาพ (Entry, TP, SL)...")
                    order_details = await asyncio.to_thread(extract_order_from_image, image_bytes)
                    
                    # Check for missing fields
                    missing_fields = []
                    if order_details.action is None: missing_fields.append("ฝั่งที่เปิด (BUY หรือ SELL)")
                    if order_details.entry_price is None: missing_fields.append("ราคาเข้า (Entry Price)")
                    if order_details.current_price is None: missing_fields.append("ราคาปัจจุบัน (Current Price)")
                    
                    if missing_fields:
                        missing_str = ", ".join(missing_fields)
                        await message.reply(f"⚠️ รูปภาพที่คุณส่งมาเห็นข้อมูลไม่ครบถ้วนครับ\nบอทมองไม่เห็นข้อมูลดังต่อไปนี้: **{missing_str}**\n\nรบกวนพิมพ์บอกข้อมูลที่ขาดหายไป หรือแคปรูปที่เห็นชัดเจนกว่านี้มาใหม่อีกครั้งนะครับ!")
                        return
                        
                    # Handle SL/TP if missing (warn but proceed)
                    sl_val = order_details.stop_loss if order_details.stop_loss is not None else 0.0
                    tp_val = order_details.take_profit if order_details.take_profit is not None else 0.0
                    
                    await message.channel.send(f"✅ อ่านค่าได้แล้ว:\n`Action: {order_details.action} | Status: {order_details.order_status} | Entry: {order_details.entry_price} | Current: {order_details.current_price} | SL: {sl_val} | TP: {tp_val}`\n\nกำลังประเมินสถานการณ์...")
                    
                    order_dict = {
                        "action": order_details.action,
                        "order_status": order_details.order_status,
                        "entry_price": order_details.entry_price,
                        "current_price": order_details.current_price,
                        "stop_loss": sl_val,
                        "take_profit": tp_val
                    }

                    # Detect if SL is hit (only for ACTIVE orders)
                    is_sl_hit = False
                    if sl_val > 0 and order_details.order_status == "ACTIVE":
                        if order_details.action.upper() == "BUY" and order_details.current_price <= sl_val:
                            is_sl_hit = True
                        elif order_details.action.upper() == "SELL" and order_details.current_price >= sl_val:
                            is_sl_hit = True
                            
                    if is_sl_hit:
                        await message.channel.send("🚨 ตรวจพบว่าออเดอร์นี้ชน Stop Loss ไปแล้ว กำลังเรียกใช้งาน Recovery Agent เพื่อหาแผนแก้เกม...")
                        crew = create_recovery_crew(order_dict)
                        result = await asyncio.to_thread(crew.kickoff)
                        plan = getattr(result, 'pydantic', None)
                        
                        if not plan:
                            await message.channel.send("❌ Error: Agent ไม่สามารถคืนค่า RecoveryPlan ได้")
                            return
                            
                        reply = f"**Recovery Plan AI (Patch 1.4.7)** 🛡️\n\n"
                        reply += f"**Action:** `{plan.action}`\n"
                        if plan.action == "RECOVERY":
                            reply += f"**Recovery Entry:** {plan.recovery_entry}\n"
                            reply += f"**Recovery SL:** {plan.recovery_sl}\n"
                            reply += f"**Recovery TP:** {plan.recovery_tp}\n"
                        reply += f"\n**Rationale:**\n{plan.rationale}\n"
                        
                        waiting_for_feedback[message.author.id] = {"order": order_dict, "advice": plan.action}
                        reply += "\n---\n**โปรดให้คะแนนคำแนะนำนี้ (0-10) โดยพิมพ์ตัวเลขตอบกลับมาได้เลยครับ** 👇"
                        await message.reply(reply)
                        return

                    # 2. Run Trade Management Agent
                    crew = create_trade_management_crew(order_dict)
                    result = await asyncio.to_thread(crew.kickoff)
                    
                    plan = getattr(result, 'pydantic', None)
                    if not plan:
                        await message.channel.send("❌ Error: Agent ไม่สามารถคืนค่า TradeManagementPlan ได้")
                        return
                    
                    # 3. Format Reply
                    action_translation = {
                        "HOLD": "ถือออเดอร์รันเทรนด์ต่อไป (HOLD)",
                        "CLOSE": "ปิดออเดอร์เก็บกำไร/ตัดขาดทุนทันที (CLOSE)",
                        "RAISE_SL": "เลื่อน Stop Loss บังหน้าทุนเพื่อป้องกันความเสี่ยง (RAISE_SL)",
                        "ADD_POSITION": "เปิดไม้เพิ่มตามแนวโน้มเดิม (ADD_POSITION)",
                        "CANCEL_PENDING": "ยกเลิกออเดอร์ล่วงหน้าที่ตั้งไว้ (CANCEL_PENDING)",
                        "WAIT_PENDING": "รอราคามาชนจุดเข้าที่ตั้งล่วงหน้าไว้ (WAIT_PENDING)"
                    }
                    action_th = action_translation.get(plan.action, plan.action)

                    reply = f"**Trade Management AI (Patch 1.4.7)** 📈\n\n"
                    reply += f"**Action:** `{action_th}`\n"
                    if plan.action in ["RAISE_SL", "HOLD", "ADD_POSITION", "WAIT_PENDING"]:
                        reply += f"**Suggested SL:** {plan.suggested_sl}\n"
                        reply += f"**Suggested TP:** {plan.suggested_tp}\n"
                    
                    reply += f"\n**Rationale:**\n{plan.rationale}\n"
                    
                    waiting_for_feedback[message.author.id] = {"order": order_dict, "advice": plan.action}
                    reply += "\n---\n**โปรดให้คะแนนคำแนะนำนี้ (0-10) โดยพิมพ์ตัวเลขตอบกลับมาได้เลยครับ** 👇"
                    
                    await message.reply(reply)
                    
                except Exception as e:
                    logger.error(f"Error processing image: {e}", exc_info=True)
                    await message.channel.send(f"❌ เกิดข้อผิดพลาดในการวิเคราะห์รูป: {str(e)}")

def run_bot():
    if not GEMINI_API_KEY:
        logger.error("GEMINI_API_KEY is missing! Fail fast.")
        exit(1)
    if not DISCORD_BOT_TOKEN:
        logger.error("DISCORD_BOT_TOKEN is missing! Fail fast.")
        exit(1)
        
    client.run(DISCORD_BOT_TOKEN)

if __name__ == "__main__":
    run_bot()
